# Generated by Django 5.2.17 on 2026-09-15 09:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('dspace_collection_uuid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('normalized_name', models.CharField(db_index=True, max_length=300, unique=True)),
                ('research_count', models.IntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-research_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_retrieved', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('duplicates_skipped', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('success', 'Completed Successfully'), ('partial', 'Completed with Errors'), ('failed', 'Failed')], default='in_progress', max_length=30)),
                ('error_details', models.TextField(blank=True, default='')),
                ('summary_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dspace_uuid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=400)),
                ('handle', models.CharField(blank=True, default='', max_length=100)),
                ('community_name', models.CharField(default='Postgraduate Masters Theses/Reports', max_length=300)),
                ('item_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='research.faculty')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dspace_uuid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.TextField(db_index=True)),
                ('abstract', models.TextField(blank=True, default='')),
                ('authors_display', models.TextField(blank=True, default='')),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('publication_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('date_issued', models.CharField(blank=True, default='', max_length=50)),
                ('faculty_name', models.CharField(blank=True, db_index=True, default='', max_length=300)),
                ('collection_name', models.CharField(blank=True, default='', max_length=300)),
                ('community', models.CharField(default='Postgraduate Masters Theses/Reports', max_length=300)),
                ('community_uuid', models.CharField(default='95cbea8b-fdc6-4d8a-9f20-d51ad2814f12', max_length=64)),
                ('handle', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('dspace_url', models.URLField(blank=True, default='', max_length=500)),
                ('bitstream_url', models.URLField(blank=True, default='', max_length=500)),
                ('item_type', models.CharField(db_index=True, default='Thesis', max_length=100)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('search_vector_text', models.TextField(blank=True, default='')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='research_items', to='research.researcher')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_items', to='research.collection')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_items', to='research.faculty')),
            ],
            options={
                'ordering': ['-publication_year', 'title'],
                'indexes': [models.Index(fields=['dspace_uuid'], name='research_re_dspace__86b1ea_idx'), models.Index(fields=['publication_year'], name='research_re_publica_ec1ebf_idx'), models.Index(fields=['faculty_name'], name='research_re_faculty_ce758a_idx'), models.Index(fields=['handle'], name='research_re_handle_31cf4f_idx')],
            },
        ),
    ]
